# Site settings
title: TripTrax
email: your-email@domain.com
description: "Mileage log. Companion to the TripTrax iOS app."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['*.json', 'Gruntfile.js', 'config.rb', 'node_modules',  'stylesheets', 'js', 'vagrant', 'F43CloudCode']
